### ISSUE TITLE
version solving   failed for flutter_localizations and flex_color_scheme

### ISSUE THREAD

**Issue by esbozos** [rydmike/flex_color_scheme#133]
I'm not sure if it's my mistake or I missed something updating the packages. But I have two days trying to run my app and apparently the only way is to downgrade flex_color_scheme to version 4, but then I lose many properties of the app with material 3. 

Flutter version: 

- Flutter 3.10.0-5.0.0.pre.33 - channel main - https://github.com/flutter/flutter.git
- Framework - revision b95cd931ae (23 minutes ago) - 2023-04-14 13:20:49 -0400
- Engine - revision ea0e1b1700
- Tools - Dart 3.1.0 (build 3.1.0-4.0.dev) - DevTools 2.23.1

**pubspec.yaml**

```yaml

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  go_router: ^6.0.8
  googleapis: ^10.1.0
  provider: ^6.0.5
  url_launcher: ^6.1.9
  flex_color_scheme: ^7.0.1
  dio: ^5.0.0
  cached_network_image: ^3.2.3
  transparent_image: ^2.0.1
  json_annotation: ^4.8.0
  flutter_secure_storage: ^8.0.0
  settings_ui: ^2.0.2
  google_fonts: ^4.0.3
  jiffy: ^6.1.0
  country_picker: ^2.0.20
  syncfusion_flutter_charts: ^21.1.35
  flutter_svg: ^2.0.4
```

Flutter run:
```bash
Resolving dependencies... (1.0s)
Because flex_seed_scheme 1.2.3 depends on material_color_utilities ^0.2.0 and no versions of flex_seed_scheme match
  >1.2.3 <2.0.0, flex_seed_scheme ^1.2.3 requires material_color_utilities ^0.2.0.
And because every version of flutter_localizations from sdk depends on material_color_utilities 0.3.0,
  flutter_localizations from sdk is incompatible with flex_seed_scheme ^1.2.3.
And because flex_color_scheme 7.0.1 depends on flex_seed_scheme ^1.2.3 and no versions of flex_color_scheme match >7.0.1
  <8.0.0, flutter_localizations from sdk is incompatible with flex_color_scheme ^7.0.1.
So, because arkadu_admin depends on both flutter_localizations from sdk and flex_color_scheme ^7.0.1, version solving
  failed.
```
Note: the app was fully functional and in fact I compiled it a couple of weeks ago without problems and published in play store.
